version: "3.7"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8888:8000"
    volumes:
      - ./geronimo/backend:/home/geronimo/backend
      - ./prod/nginx:/etc/nginx/conf.d
      - ./prod/logs:/var/logs/nginx
    depends_on: 
      - api
  api:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py migrate && gunicorn django_backend.wsgi -w 8 -t 300 -b 0.0.0.0:8000"
    volumes:
      - ./geronimo/backend:/home/geronimo/backend
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on: 
      - db
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ./database-backup:/database-backup
    env_file:
      - ./.env.dev.db
volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
